local surround = require("simple-surr.surround")

describe("simple-surr", function()
    before_each(function()
        vim.opt.rtp:append(vim.fn.getcwd())
        surround.set_options({ space = "never" })
        vim.cmd("enew!")
    end)

    it("normalizes reversed ranges", function()
        vim.api.nvim_buf_set_lines(0, 0, -1, false, { "foo bar" })
        surround.surround_range("()", { 0, 1, 3, 0 }, { 0, 1, 1, 0 }, false)
        assert.equals("(foo) bar", vim.api.nvim_get_current_line())
    end)

    it("surrounds the word under cursor only", function()
        vim.api.nvim_set_current_line("foo foo")
        vim.api.nvim_win_set_cursor(0, { 1, 5 })
        surround.surround_word("[]", false)
        assert.equals("foo [foo]", vim.api.nvim_get_current_line())
    end)

    it("surrounds line via operator", function()
        vim.api.nvim_buf_set_lines(0, 0, -1, false, { "alpha", "beta" })
        vim.fn.setpos("'[", { 0, 1, 1, 0 })
        vim.fn.setpos("']", { 0, 1, 5, 0 })
        surround.operator_surround("{}", "line", false)
        assert.equals("{alpha}", vim.api.nvim_buf_get_lines(0, 0, 1, false)[1])
    end)

    it("surrounds line content without leading/trailing spaces", function()
        vim.api.nvim_set_current_line("  hello world  ")
        vim.fn.setpos(".", { 0, 1, 1, 0 })
        surround.surround_line("()", nil, false)
        assert.equals("  (hello world)  ", vim.api.nvim_get_current_line())
    end)

    it("surrounds line with leading spaces only", function()
        vim.api.nvim_set_current_line("   content")
        vim.fn.setpos(".", { 0, 1, 1, 0 })
        surround.surround_line("[]", nil, false)
        assert.equals("   [content]", vim.api.nvim_get_current_line())
    end)

    it("surrounds line with trailing spaces only", function()
        vim.api.nvim_set_current_line("content   ")
        vim.fn.setpos(".", { 0, 1, 1, 0 })
        surround.surround_line("{}", nil, false)
        assert.equals("{content}   ", vim.api.nvim_get_current_line())
    end)

    it("applies spacing policy", function()
        vim.api.nvim_set_current_line("word")
        vim.api.nvim_win_set_cursor(0, { 1, 1 })
        surround.surround_word("()", true)
        assert.equals("( word )", vim.api.nvim_get_current_line())
    end)

    it("accepts custom surround pairs via setup", function()
        require("simple-surr").setup({
            custom_surround_pairs = {
                ["!"] = { "!", "!" },
            },
        })
        vim.api.nvim_set_current_line("wow")
        vim.api.nvim_win_set_cursor(0, { 1, 1 })
        surround.surround_word("!", false)
        assert.equals("!wow!", vim.api.nvim_get_current_line())
    end)

    it("surrounds multiple elements with comma separator", function()
        vim.api.nvim_set_current_line("foo, bar, baz")
        vim.fn.setpos("v", { 0, 1, 1, 0 })
        vim.fn.setpos(".", { 0, 1, 14, 0 })
        surround.surround_multi('"', ",", false)
        assert.equals('"foo", "bar", "baz"', vim.api.nvim_get_current_line())
    end)

    it("preserves spaces in multi-surround when enabled", function()
        vim.api.nvim_set_current_line("foo, bar, baz")
        vim.fn.setpos("v", { 0, 1, 1, 0 })
        vim.fn.setpos(".", { 0, 1, 14, 0 })
        surround.surround_multi('"', ",", true)
        assert.equals('"foo", "bar", "baz"', vim.api.nvim_get_current_line())
    end)

    it("handles csv-style multi-surround without spaces", function()
        vim.api.nvim_set_current_line("foo,bar,baz")
        vim.fn.setpos("v", { 0, 1, 1, 0 })
        vim.fn.setpos(".", { 0, 1, 11, 0 })
        surround.surround_multi('"', ",", false)
        assert.equals('"foo","bar","baz"', vim.api.nvim_get_current_line())
    end)

    it("handles custom separator in multi-surround", function()
        vim.api.nvim_set_current_line("foo; bar; baz")
        vim.fn.setpos("v", { 0, 1, 1, 0 })
        vim.fn.setpos(".", { 0, 1, 14, 0 })
        surround.surround_multi("()", ";", false)
        assert.equals("(foo); (bar); (baz)", vim.api.nvim_get_current_line())
    end)

    it("surrounds with prefix and suffix", function()
        vim.api.nvim_set_current_line("x")
        vim.fn.setpos("v", { 0, 1, 1, 0 })
        vim.fn.setpos(".", { 0, 1, 1, 0 })
        surround.surround_prefix_suffix("if (", ")")
        assert.equals("if (x)", vim.api.nvim_get_current_line())
    end)

    it("surrounds with HTML comment prefix/suffix", function()
        vim.api.nvim_set_current_line("content")
        vim.fn.setpos("v", { 0, 1, 1, 0 })
        vim.fn.setpos(".", { 0, 1, 7, 0 })
        surround.surround_prefix_suffix("<!-- ", " -->")
        assert.equals("<!-- content -->", vim.api.nvim_get_current_line())
    end)

    it("unwraps word with auto-detect", function()
        vim.api.nvim_set_current_line('"hello"')
        vim.api.nvim_win_set_cursor(0, { 1, 3 })
        surround.unwrap("")
        assert.equals("hello", vim.api.nvim_get_current_line())
    end)

    it("unwraps word with specified style", function()
        vim.api.nvim_set_current_line("[world]")
        vim.api.nvim_win_set_cursor(0, { 1, 2 })
        surround.unwrap("[")
        assert.equals("world", vim.api.nvim_get_current_line())
    end)

    it("unwraps selection with auto-detect", function()
        vim.api.nvim_set_current_line('"test"')
        vim.fn.setpos("v", { 0, 1, 1, 0 })
        vim.fn.setpos(".", { 0, 1, 6, 0 })
        surround.unwrap_selection("")
        assert.equals("test", vim.api.nvim_get_current_line())
    end)

    it("unwraps selection with specified style", function()
        vim.api.nvim_set_current_line("{example}")
        vim.fn.setpos("v", { 0, 1, 1, 0 })
        vim.fn.setpos(".", { 0, 1, 9, 0 })
        surround.unwrap_selection("{")
        assert.equals("example", vim.api.nvim_get_current_line())
    end)
end)
